name: push-workflow 2
on: push

jobs:
  push-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hello world
      - name: step2
        run: |    # 2개 이상 입력시 멀티 라인 
            echo hello world
            echo github action
